### ISSUE TITLE
frontのリポジトリにpushする

### ISSUE THREAD

**Issue by shamisonn** [sakaba-project/sakaba-front#1]
* frontリポジトリ: https://github.com/sakaba-project/sakaba-front.git
* このリポジトリにフロントのコードを入れる

**Comment by naoi217** [comment]
認証情報の保存にosxkeychain を使っていたみたいで前のアカウントの認証情報でpushしようとしてpushできない罠にハマってました。
ずっと
```
remote: You must verify your email address.
remote: See https://github.com/settings/emails.
```
って怒られてドツボにはまりました。クソが

**Comment by shamisonn** [comment]
doneにあるのでcloseしちゃいます！
